import 'dart:async';
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:gajahweb/components/service_control_card.dart';
import 'package:gajahweb/utils/process.dart';
import 'package:gajahweb/utils/terminal_context.dart';
import 'package:provider/provider.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:url_launcher/url_launcher.dart';

class Pgadmincontrol extends StatefulWidget {
  const Pgadmincontrol({super.key});

  @override
  State<Pgadmincontrol> createState() => _PgadmincontrolState();
}

class _PgadmincontrolState extends State<Pgadmincontrol>
    with WidgetsBindingObserver {
  bool status = false;
  bool _isManualChanging = false;
  Timer? _statusTimer;

  bool _isInstalled = true;

  String get _pgadminBasePath {
    if (Platform.isLinux) {
      final home = Platform.environment['HOME'] ?? '';
      return '$home/.gajahweb/pgadmin';
    }
    return r'C:\gajahweb\pgadmin';
  }

  String get _venvPath => Platform.isLinux ? '$_pgadminBasePath/venv' : '$_pgadminBasePath\\venv';

  String get _pythonExe => Platform.isLinux ? '$_venvPath/bin/python3' : '$_venvPath\\Scripts\\python.exe';

  String get _pipExe => Platform.isLinux ? '$_venvPath/bin/pip' : '$_venvPath\\Scripts\\pip.exe';

  static const String _defaultPort = '5050';
  static const Duration _statusCheckDelay = Duration(seconds: 3);

  Future<void> sendTerminal(String message) async {
    final terminalAdd = Provider.of<Terminalcontext>(
      context,
      listen: false,
    ).add;
    terminalAdd(message);
  }

  /// Auto-generates config_local.py so pgAdmin uses the correct paths and port.
  Future<void> _writeConfigLocal(String port) async {
    final dataDir = '$_pgadminBasePath\\data';
    final logFile = '$_pgadminBasePath\\pgadmin4.log';
    final configPath = '$_pgadminBasePath\\config_local.py';

    await Directory(dataDir).create(recursive: true);

    final configContent =
        '''# Auto-generated by GajahWeb – do not edit manually.
DATA_DIR = r'$dataDir'
LOG_FILE = r'$logFile'
DEFAULT_SERVER_PORT = $port
DEFAULT_SERVER = '127.0.0.1'
SERVER_MODE = False
MASTER_PASSWORD_REQUIRED = False
UPGRADE_CHECK_ENABLED = False
''';

    await File(configPath).writeAsString(configContent);
  }

  Future<void> _checkPgadminStatus() async {
    if (_isManualChanging) return;
    final prefs = await SharedPreferences.getInstance();
    final port = prefs.getString('pgadminPort') ?? _defaultPort;
    final portInUse = !(await isPortAvailable(port));
    if (mounted) {
      setState(() {
        status = portInUse;
      });
    }
  }

  Future<void> _checkIfInstalled() async {
    final installed = await File(_pythonExe).exists();
    if (mounted) {
      setState(() {
        _isInstalled = installed;
      });
    }
  }

  Future<void> _installPgadmin() async {
    if (mounted) {
      setState(() {
        _isManualChanging = true;
      });
    }
    sendTerminal('Memulai instalasi pgAdmin 4...');
    
    try {
      await Directory(_pgadminBasePath).create(recursive: true);
      
      sendTerminal('Membuat virtual environment...');
      final pythonCmd = Platform.isLinux ? 'python3' : 'python';
      final venvResult = await Process.run(pythonCmd, ['-m', 'venv', 'venv'], workingDirectory: _pgadminBasePath);
      if (venvResult.exitCode != 0) {
        sendTerminal('Gagal membuat venv: ${venvResult.stderr}');
        throw Exception('Venv creation failed');
      }

      sendTerminal('Mengunduh dan menginstal pgadmin4 (bisa memakan waktu)...');
      final installResult = await Process.run(_pipExe, ['install', 'pgadmin4'], workingDirectory: _pgadminBasePath);
      if (installResult.exitCode != 0) {
        sendTerminal('Gagal menginstal pgadmin4: ${installResult.stderr}');
        throw Exception('Pgadmin4 installation failed');
      }
      
      sendTerminal('Instalasi pgAdmin 4 selesai.');
      if (mounted) {
        setState(() {
          _isInstalled = true;
        });
      }
    } catch (e) {
      sendTerminal('Error instalasi: $e');
    } finally {
      if (mounted) {
        setState(() {
          _isManualChanging = false;
        });
      }
    }
  }

  Future<void> _triggerPgadmin(bool value) async {
    _isManualChanging = true;
    final prefs = await SharedPreferences.getInstance();
    final port = prefs.getString('pgadminPort') ?? _defaultPort;

    try {
      if (value) {
        await _writeConfigLocal(port);
        final scriptResult = await Process.run(_pythonExe, ['-c', 'import os, pgadmin4; print(os.path.join(os.path.dirname(pgadmin4.__file__), "pgAdmin4.py"))']);
        final pgadminScript = scriptResult.stdout.toString().trim();
        
        await Process.start(
          _pythonExe,
          [pgadminScript],
          workingDirectory: _pgadminBasePath,
          runInShell: false,
          mode: ProcessStartMode.detached,
          environment: {
            ...Platform.environment,
            'PGADMIN_CONFIG_LOCAL': '$_pgadminBasePath\\config_local.py',
          },
        );
        sendTerminal(
          'Memulai pgAdmin 4 di port $port\n'
          'Jalankan browser dan buka http://localhost:$port',
        );
      } else {
        await killProcessByPort(port);
        sendTerminal(
          'Menghentikan pgAdmin 4 [port $port]\nBerhasil Dilakukan!',
        );
      }
    } catch (error) {
      sendTerminal('Gagal mengubah status pgAdmin: $error');
    }

    if (mounted) {
      setState(() {
        status = value;
      });
    }

    Future.delayed(_statusCheckDelay, () {
      _isManualChanging = false;
      _checkPgadminStatus();
    });
  }

  Future<void> _launchPgAdmin() async {
    final prefs = await SharedPreferences.getInstance();
    final port = prefs.getString('pgadminPort') ?? _defaultPort;
    final uri = Uri.parse('http://localhost:$port');
    await launchUrl(uri);
  }

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
    _checkIfInstalled().then((_) => _checkPgadminStatus());
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (state == AppLifecycleState.resumed) {
      _checkPgadminStatus();
    }
  }

  @override
  void dispose() {
    _statusTimer?.cancel();
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return ServiceControlCard(
      serviceName: 'pgAdmin 4',
      statusText: status ? 'Running' : 'Stopped',
      statusColor: status ? Colors.green : Colors.red,
      value: status,
      onChanged: _triggerPgadmin,
      onLaunch: status ? _launchPgAdmin : null,
      imageAsset: 'assets/pgadmin.png',
      isInstalled: _isInstalled,
      onInstall: _installPgadmin,
    );
  }
}
